apiVersion: yaook.cloud/v1
kind: NovaDeployment
metadata:
  name: nova
  namespace: openstack
spec:
  targetRelease: "2024.1"
  
  region:
    name: RegionOne
  
  keystoneRef:
    name: keystone
  
  issuerRef:
    name: ca-issuer
  
  database:
    api:
      replicas: 1
      storageClassName: longhorn
      storageSize: 5Gi
      proxy: {}
      backup:
        schedule: "0 * * * *"
    placement:
      replicas: 1
      storageClassName: longhorn
      storageSize: 5Gi
      proxy: {}
      backup:
        schedule: "0 * * * *"
    cell0:
      replicas: 1
      storageClassName: longhorn
      storageSize: 5Gi
      proxy: {}
      backup:
        schedule: "0 * * * *"
    cell1:
      replicas: 1
      storageClassName: longhorn
      storageSize: 5Gi
      proxy: {}
      backup:
        schedule: "0 * * * *"
  
  eviction:
    volumeLockDurationSeconds: 30
  
  messageQueue:
    cell1:
      replicas: 1
  
  memcached:
    replicas: 1
    memory: 1024
    connections: 2000
  
  api:
    replicas: 1
    ingress:
      fqdn: "nova.region.com"
      port: 443
      ingressClassName: nginx
  
  conductor:
    replicas: 1
  
  placement:
    replicas: 1
    ingress:
      fqdn: "placement.region.com"
      port: 443
      ingressClassName: nginx
  
  scheduler:
    replicas: 1
  
  vnc:
    replicas: 1
    ingress:
      fqdn: "vnc.region.com"
      port: 443
      ingressClassName: nginx
  
  metadata:
    replicas: 1
  
  novaConfig:
    DEFAULT:
      debug: false
      cpu_allocation_ratio: 4.0
      ram_allocation_ratio: 1.0
      reserved_host_memory_mb: 2048
  
  compute:
    configTemplates:
      - nodeSelectors:
        - matchLabels:
            compute.yaook.cloud/enabled: "true"
        novaComputeConfig:
          DEFAULT:
            debug: false
          libvirt:
            virt_type: kvm
            cpu_mode: host-passthrough
            images_type: rbd
            images_rbd_pool: vms
            images_rbd_ceph_conf: /etc/ceph/ceph.conf
            rbd_user: nova
            disk_cachemodes: "network=writeback"
            hw_disk_discard: unmap
            inject_password: false
            inject_key: false
            inject_partition: -2
        volumeBackends:
          ceph:
            enabled: true
            keyringSecretName: ceph-client-nova-key
            user: nova
            uuid: "e3a4e143-15ea-467c-8859-730731ab1a64"
            cephConfig:
              global:
                mon_host: "[v2:10.10.28.10:3300/0,v1:10.10.28.10:6789/0] [v2:10.10.28.6:3300/0,v1:10.10.28.6:6789/0] [v2:10.10.28.7:3300/0,v1:10.10.28.7:6789/0] [v2:10.10.28.8:3300/0,v1:10.10.28.8:6789/0]"
                fsid: "ad9e8f76-3aae-11f0-9498-0fcbb987ca56"
  
  databaseCleanup:
    schedule: "0 0 * * *"
    deletionTimeRange: 60
  
  placementCleanup:
    schedule: "*/5 * * * *"
